apiVersion: apps/v1
kind: Deployment
metadata:
  name: stimulus-api
  namespace: stimulus-dev
  labels:
    app: stimulus-api
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stimulus-api
  template:
    metadata:
      labels:
        app: stimulus-api
      annotations:
        proxy.istio.io/config: |
          proxyStatsMatcher:
            inclusionPrefixes:
            - "cluster.outbound"
            - "listener"
            - "cluster_manager"
            - "listener_manager"
            - "server"
            - "cluster.xds-grpc"
        traffic.sidecar.istio.io/includeInboundPorts: "8000"
    spec:
      containers:
      - name: stimulus-api
        image: stimulus.azurecr.io/stimulus-api:__IMAGE_TAG__
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: ["stimulus_data_engine.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
        - name: HOST
          value: "0.0.0.0"
        - name: STIMULUS_API_KEY
          valueFrom:
            secretKeyRef:
              name: stimulus-secrets
              key: stimulus-api-key
        - name: DATABRICKS_HOST
          valueFrom:
            secretKeyRef:
              name: stimulus-secrets
              key: databricks-host
        - name: DATABRICKS_TOKEN
          valueFrom:
            secretKeyRef:
              name: stimulus-secrets
              key: databricks-token
        - name: DATABRICKS_HTTP_PATH
          valueFrom:
            secretKeyRef:
              name: stimulus-secrets
              key: databricks-http-path
        - name: NEO4J_URI
          valueFrom:
            secretKeyRef:
              name: stimulus-secrets
              key: neo4j-uri
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: stimulus-secrets
              key: openai-api-key
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: stimulus-secrets
              key: azure-openai-endpoint
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: data-engine
#   labels:
#     app: data-engine
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: data-engine
#   template:
#     metadata:
#       labels:
#         app: data-engine
#     spec:
#       containers:
#         - name: data-engine
#           image: ghcr.io/org/data-engine:latest
#           ports:
#             - containerPort: 8000
#           env:
#             - name: ENVIRONMENT
#               value: "production"
#             - name: DATABASE_URL
#               valueFrom:
#                 secretKeyRef:
#                   name: stimulus-secrets
#                   key: database_url
#           volumeMounts:
#             - name: ssh-key-volume
#               mountPath: "/root/.ssh"
#               readOnly: true
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "250m"
#             limits:
#               memory: "512Mi"
#               cpu: "500m"
#           readinessProbe:
#             httpGet:
#               path: /health
#               port: 8000
#             initialDelaySeconds: 5
#             periodSeconds: 10
#           livenessProbe:
#             httpGet:
#               path: /health
#               port: 8000
#             initialDelaySeconds: 10
#             periodSeconds: 30
#       volumes:
#         - name: ssh-key-volume
#           secret:
#             secretName: github-ssh-key
#             defaultMode: 0600
#             items:
#               - key: ssh-privatekey
#                 path: id_ed25519
#       imagePullSecrets:
#         - name: ghcr-secret
