apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"stimulus-data-engine-gateway","namespace":"stimulus-dev"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["sde-dev.getstimulus.ai","sde-dev-api.getstimulus.ai"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  creationTimestamp: "2025-04-28T04:32:56Z"
  generation: 3
  name: stimulus-data-engine-gateway
  namespace: stimulus-dev
  resourceVersion: "423073116"
  uid: 3e5b5473-a346-41e0-bfae-0246b8291c1f
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - sde-dev.getstimulus.ai
    - sde-dev-api.getstimulus.ai
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: stimulus-tls
      mode: SIMPLE
