apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stimulus-ingress
  namespace: stimulus-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/$1
spec:
  tls:
  - hosts:
    - sde-dev.getstimulus.ai
    - sde-dev-api.getstimulus.ai
    secretName: stimulus-tls
  rules:
  - host: sde-dev.getstimulus.ai
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: stimulus-web
            port:
              number: 3000
  - host: sde-dev-api.getstimulus.ai
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: stimulus-api
            port:
              number: 8000
