apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: stimulus-data-engine
  namespace: stimulus-dev
  annotations:
    # Ensure proper header handling
    proxy.istio.io/config: |
      {
        "gatewayTopology": {
          "numTrustedProxies": 2,
          "forwardClientCertDetails": "SANITIZE_SET"
        }
      }
spec:
  gateways:
    - stimulus-dev/stimulus-data-engine-gateway
  hosts:
    - sde-dev.getstimulus.ai
    - sde-dev-api.getstimulus.ai
  http:
    # ========================
    # HEALTH CHECK ENDPOINTS
    # ========================
    - match:
        - authority:
            exact: sde-dev-api.getstimulus.ai
          uri:
            exact: /health
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 10s

    # ========================
    # CORS PREFLIGHT HANDLING
    # ========================
    - match:
        - method:
            exact: OPTIONS
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      headers:
        response:
          set:
            access-control-allow-origin: "https://sde-dev.getstimulus.ai"
            access-control-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
            access-control-allow-headers: "Authorization, Content-Type, X-Requested-With"
            access-control-allow-credentials: "true"
            access-control-max-age: "86400"
      timeout: 10s

    # ========================
    # VECTOR SEARCH ENDPOINT
    # ========================
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/vector-search
      rewrite:
        uri: /api/v1/vector-search/search
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      headers:
        request:
          set:
            x-forwarded-host: sde-dev.getstimulus.ai
            x-forwarded-proto: https
            x-original-uri: /api/vector-search
          add:
            x-auth-request-headers: "Authorization,Content-Type"
        response:
          set:
            access-control-allow-origin: "https://sde-dev.getstimulus.ai"
            access-control-allow-credentials: "true"
      corsPolicy:
        allowOrigins:
          - exact: https://sde-dev.getstimulus.ai
        allowMethods:
          - POST
          - OPTIONS
        allowHeaders:
          - authorization
          - content-type
          - x-requested-with
        allowCredentials: true
        exposeHeaders:
          - authorization
          - x-auth-request-redirect
      timeout: 300s

    # ========================
    # FRONTEND API ROUTES
    # ========================
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            exact: /api/clients
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 10s

    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/assessment
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 10s

    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/rfx
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 10s

    # ========================
    # DATABRICKS SQL PROXY
    # ========================
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/proxy/databricks-sql
      rewrite:
        uri: /api/v1/databricks-sql
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      headers:
        request:
          set:
            x-forwarded-host: sde-dev.getstimulus.ai
      timeout: 300s

    - match:
        - authority:
            exact: sde-dev-api.getstimulus.ai
          uri:
            prefix: /api/v1/databricks-sql
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 300s

    # ========================
    # COPILOT KIT
    # ========================
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/copilotkit
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 120s

    # ========================
    # CATCH-ALL ROUTES
    # ========================
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      headers:
        request:
          set:
            x-forwarded-host: sde-dev.getstimulus.ai
            x-forwarded-proto: https
      timeout: 300s

    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 30s

    - match:
        - authority:
            exact: sde-dev-api.getstimulus.ai
          uri:
            prefix: /
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 300s
