apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: stimulus-data-engine
  namespace: stimulus-dev
spec:
  gateways:
    - stimulus-dev/stimulus-data-engine-gateway
  hosts:
    - sde-dev.getstimulus.ai
    - sde-dev-api.getstimulus.ai
  http:
    # Default route with CORS policy for frontend
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /
      corsPolicy:
        allowOrigins:
          - exact: "https://sde-dev.getstimulus.ai"
        allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allowHeaders: ["Authorization", "Content-Type", "X-Requested-With"]
        exposeHeaders: ["Authorization", "Content-Type"]
        allowCredentials: true
        maxAge: "24h"
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 30s

    # Health Check
    - match:
        - authority:
            exact: sde-dev-api.getstimulus.ai
          uri:
            exact: /health
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 10s

    # Frontend API routes
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            exact: /api/clients
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 10s

    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/assessment
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 10s

    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/rfx
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 10s

    # Vector Search from frontend
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            exact: /api/vector-search
      rewrite:
        uri: /api/v1/vector-search/search
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      headers:
        request:
          set:
            x-forwarded-host: "sde-dev.getstimulus.ai"
        response:
          set:
            access-control-allow-origin: "https://sde-dev.getstimulus.ai"
            access-control-allow-credentials: "true"
      timeout: 300s

    # Vector Search direct API access
    - match:
        - authority:
            exact: sde-dev-api.getstimulus.ai
          uri:
            exact: /api/vector-search
      rewrite:
        uri: /api/v1/vector-search/search
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 300s

    # Databricks SQL Proxy
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/proxy/databricks-sql/
      rewrite:
        uri: /api/v1/databricks-sql/
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 300s

    # CopilotKit
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/copilotkit
      route:
        - destination:
            host: stimulus-web.stimulus-dev.svc.cluster.local
            port:
              number: 3000
      timeout: 120s

    # API catch-all
    - match:
        - authority:
            exact: sde-dev.getstimulus.ai
          uri:
            prefix: /api/
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 300s

    # API direct access catch-all
    - match:
        - authority:
            exact: sde-dev-api.getstimulus.ai
          uri:
            prefix: /
      route:
        - destination:
            host: stimulus-api.stimulus-dev.svc.cluster.local
            port:
              number: 8000
      timeout: 300s
