apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stimulus-ingress
  namespace: stimulus-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

    # SSL/Redirects
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    # CORS Configuration (critical fix: use "always" for 4xx/5xx)
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://sde-dev.getstimulus.ai"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: "86400"

    # Critical Fix: Force headers to persist on 4xx/5xx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: https://sde-dev.getstimulus.ai" always;
      more_set_headers "Access-Control-Allow-Credentials: true" always;
      more_set_headers "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS" always;
      more_set_headers "Access-Control-Allow-Headers: Authorization, Content-Type" always;
      proxy_set_header Authorization $http_authorization;  # Ensures auth header reaches backend

    # Body and Buffering
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"

    # Path Handling
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-underscores-in-headers: "true"

spec:
  tls:
    - hosts:
        - sde-dev.getstimulus.ai
        - sde-dev-api.getstimulus.ai
      secretName: stimulus-tls
  rules:
    - host: sde-dev.getstimulus.ai
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: stimulus-web
                port:
                  number: 3000
    - host: sde-dev-api.getstimulus.ai
      http:
        paths:
          - path: /api/v1/(.*)
            pathType: Prefix
            backend:
              service:
                name: stimulus-api
                port:
                  number: 8000
