apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: stimulus-data-engine-gateway
  namespace: stimulus-dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - sde-dev.getstimulus.ai
    - sde-dev-api.getstimulus.ai
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: stimulus-tls
      mode: SIMPLE
  # Add HTTP->HTTPS redirect (recommended)
  - hosts:
    - sde-dev.getstimulus.ai
    - sde-dev-api.getstimulus.ai
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
